### ISSUE TITLE
Add Threshold for languages

### ISSUE THREAD

**Issue by Nudin** [bukinoshita/open-source#19]
If the languages for a project are 99.8% X and 0.2% Y, the language Y should not be assigned to the issues, because they are very likely not connected to this. The threshold could be something between 1 and 5 %.

A typical example are shell scripts which can be found in most repos.

**Comment by bukinoshita** [comment]
Cool! Totally agree 👍 

The API may return an object like this:

```js
{
  "Java": 1611293,
  "HTML": 163038,
  "JavaScript": 53682,
  "CSS": 14541,
  "Shell": 13314,
  "Python": 6916,
  "Perl": 5111,
  "Scala": 3952,
  "Ruby": 427,
  "Batchfile": 277
}
```

Maybe we should return only languages with value higher than 10K? In this case only `Java`, `HTML`, `JavasScript`, `CSS` and `Shell` would be assigned to the issue.
